/**
 * Created by kael on 15/6/3.
 */

var desc = {
    '/register':{
        'post':{
            'desc':'注册',
            'param':{
                'un':'用户名',
                'pwd':'密码'
            },
            'return':{
                '成功失败与错误码':1
            }
        }
    },
    '/requestTourName':{
        'get':{
            'desc':'获得一个游客账号',
            'param':{
                'udid':'udid'
            },
            'return':{
                'un':'用户名',
                '密码格式暂定为用户名的md5':'',
                '成功失败与错误码':1
            }
        }
    },
    '/bindTourNameThird':{
        'post':{
            'desc':'绑定第三方账号',
            'param':{
                'udid':'udid',
                'pt':'平台类别 1GameCenter 2Facebook等,待定',
                'pu':'平台独立id'
            },
            'return':{
                'un':'用户名 成功绑定返回新用户名,如果已绑定过返回错误码的同时也会返回可用用户名,当第三方登陆/绑定第三方账号的时候都是调用这个接口',
                '成功失败与错误码':1
            }
        }
    },
    '/bindTourName':{
        'post':{
            'desc':'绑定游客账号到新用户名密码',
            'param':{
                'udid':'udid',
                'un':'新用户名',
                'pwd':'新密码'
            },
            'return':{
                '成功失败与错误码':1
            }
        }
    },

    '/login':{
        'post':{
            'desc':'登陆',
            'param':{
                'un':'用户名',
                'pwd':'密码',
                'zid':'目标分区ID',
                'm5':'机器标识码'
            },
            'return':{
                '成功失败与错误码':1,
                'uid':'用户全局ID,如果没有用户',
                'userDetail':'用户详细信息,如果选择分区内有角色',
                'role.ne':'下一个体力增加剩余时间',
                'role.m5':'角色唯一码'
            }
        }
    },
    '/userDetail':{
        'post':{
            'desc':'创建用户实例',
            'param':{
                'req.body.uid':'用户id,User表,登陆成功返回',
                'req.body.zid':'目标分区ID',
                'req.body.nn':'nickname',
                'req.body.g':'gender'
            },
            'return':{
                '成功失败与错误码':1
            }
        }
    },
    '/userDetail/id':{
        'get':{
            'desc':'获取用户实例',
            'param':{
                'req.body.uid':'用户id,User表,登陆成功返回',
                'req.body.zid':'目标分区ID'
            },
            'return':{
                '成功失败与错误码':1,
                'userDetail实体':'成功返回'
            }
        },
        'delete':{
            'desc':'删除用户实例',
            'param':{
                'req.query.uid':'用户id,User表,登陆成功返回',
                'req.query.zid':'目标分区ID'
            },
            'return':{
                '成功失败与错误码':1
            }
        }
    },
    '/userDetailUpdate':{
        'post':{
            'desc':'修改用户实例',
            'param':{
                'req.body.uid':'用户id,User表,登陆成功返回',
                'req.body.zid':'目标分区ID',
                'req.body.setting':'修改字段新值,内嵌字段形如{"task.t1001.am":3},如果没有会创建',
                'create string as':'{"uid":"556da81322c2bc4106602997","zid":0,"setting":{"task.t1001":{"am1":2,"am2":0,"st":3}}}',
                'update string as':'{"uid":"556da81322c2bc4106602997","zid":0,"setting":{"task.t1001.am1":3}}'
            },
            'return':{
                '成功失败与错误码':1,
                'userDetail实体':'成功返回修改后的内容'
            }
        }
    },
    '/markEvidenceTime':{
        'post':{
            'desc':'创建物证开始鉴证时间',
            'param':{
                'req.body.uid':'用户id,User表,登陆成功返回',
                'req.body.zid':'目标分区ID',
                'req.body.cid':'物证所在案件ID',
                'req.body.eid':'物证物品ID'
            },
            'return':{
                '成功失败与错误码':1,
                'total':'这个物证鉴证总时间'
            }
        }
    },
    '/markEvidenceTimeOver':{
        'post':{
            'desc':'物证鉴证完成',
            'param':{
                'req.query.uid':'用户id,User表,登陆成功返回',
                'req.query.zid':'目标分区ID',
                'req.body.cid':'物证所在案件ID',
                'req.query.eid':'物证物品ID'
            },
            'return':{
                '成功失败与错误码':1,
                'left':'剩余多少时间可完成,如果不能完成'
            }
        }
    },
    '/markEvidenceTimeOverNow':{
        'post':{
            'desc':'物证立即鉴证完成',
            'param':{
                'req.query.uid':'用户id,User表,登陆成功返回',
                'req.query.zid':'目标分区ID',
                'req.body.cid':'物证所在案件ID',
                'req.query.eid':'物证物品ID'
            },
            'return':{
                '成功失败与错误码':1,
                'leftGem':'剩余元宝'
            }
        }
    },
    '/taskComplete':{
        'post':{
            'desc':'完成某条任务,删除任务记录',
            'param':{
                'req.body.uid':'用户id,User表,登陆成功返回',
                'req.body.zid':'目标分区ID',
                'req.body.tid':'任务ID'
            },
            'return':{
                '成功失败与错误码':1,
                'tid':'完成的任务ID',
                'inc':'增加的体力、金钱',
                'set':'caseInfo更新'
            }
        }
    },
    '/energy':{
        'post':{
            'desc':'体力增减',
            'param':{
                'req.body.uid':'用户id,User表,登陆成功返回',
                'req.body.zid':'目标分区ID',
                'req.body.cost':'正值为增加体力,负值为扣掉体力'
            },
            'return':{
                '成功失败与错误码':1,
                'left':'剩余多少时间可增加体力,如果不能增加'
            }
        }
    },
    '/energyTime':{
        'post':{
            'desc':'体力定时增减',
            'param':{
                'req.body.uid':'用户id,User表,登陆成功返回',
                'req.body.zid':'目标分区ID',
                'req.body.cost':'体力'
            },
            'return':{
                '成功失败与错误码':1,
                'left':'剩余多少时间可增加体力,如果不能增加'
            }
        }
    },
    '/caseRecord/id':{
        'get':{
            'desc':'查询具体的案件记录',
            'param':{
                'req.query.uid':'用户id,User表',
                'req.query.zid':'目标分区ID',
                'req.query.cid':'案件id'
            },
            'return':{
                '成功失败与错误码':1,
                '案件信息数据结构':1,
                '案件物证鉴证时间戳':1
            }
        }
    },
    '/statistics':{
        'post':{
            'desc':'统计信息',
            'param':{
                'req.query.uid':'用户id,User表',
                'req.query.zid':'目标分区ID',
                'req.query.sta':'设置'
            },
            'return':{
                '成功失败与错误码':1,
                '案件信息数据结构':1
            }
        }
    },
    '/sign':{
        'post':{
            'desc':'签到',
            'param':{
                'req.body.uid':'用户id,User表',
                'req.body.zid':'目标分区ID'
            },
            'return':{
                '成功失败与错误码':1,
                'sign':'签到奖励',
                't':'签到日记录表',
                'seq':'当前连续签到记录',
                's':'当前连续签到阶段,连续3天,5天...'
            }
        },
        'get':{
            'desc':'获取签到',
            'param':{
                'req.query.uid':'用户id,User表',
                'req.query.zid':'目标分区ID'
            },
            'return':{
                '成功失败与错误码':1,
                't':'签到日记录表',
                'seq':'当前连续签到记录',
                's':'当前连续签到阶段,连续3天,5天...'
            }
        }
    },
    '/signSeqAward':{
        'post':{
            'desc':'连续签到领奖',
            'param':{
                'req.body.uid':'用户id,User表',
                'req.body.zid':'目标分区ID',
                'req.body.d':'要领几天的'
            },
            'return':{
                '成功失败与错误码':1,
                sign:'奖励'
            }
        }
    },
    '/activity_list':{
        'get':{
            'desc':'获取当前活动列表',
            'return':{
                '成功失败与错误码':1,
                '活动结构体':1
            }
        }
    },
    '/syncStatus':{
        'get':{
            'desc':'同步当前状态',
            'param':{
                'req.query.uid':'用户id,User表',
                'req.query.zid':'目标分区ID'
            },
            'return':{
                '成功失败与错误码':1,
                'sr':'签到记录',
                'unread':'未读邮件',
                'tj':'当期活动列表'
            }
        }
    },
    '/findClubByName':{
        'get':{
            'desc':'查找公会',
            'param':{
                'req.query.cn':'公会名称,Club表'
            },
            'return':{
                '成功失败与错误码':1,
                'data':'公会记录',
            }
        }
    },
    '/modifyClue':{
        'post':{
            'desc':'修改公会',
            'param':{
                'req.body.intdc':'公会介绍,Club表',
                'req.body.uid':'用户id,User表',
                'req.body.cid':'公会id,Club表',
                'req.body.exp':'公会经验,club表'
            },
            'return':{
                '成功失败与错误码':1,
            }
        }
    },
    '/getAllClub':{
        'post':{
            'desc':'获取所有公会',
            'param':{
                'req.body.sp':'起始页',
                'req.body.ep':'末尾页'
            },
            'return':{
                '成功失败与错误码':1,
                'd':'公会数据'
            }
        }
    },
    '/getClubByCid':{
        'post':{
            'desc':'获取公会的信息',
            'param':{
                'req.query.cid':'公会id,Club表'
            },
            'return':{
                '成功失败与错误码':1,
                'data':'公会数据',
                'club':''
            }
        }
    },
    '/createClub':{
        'post':{
            'desc':'创建公会',
            'param':{
                'req.body.cn':'公会名称,Club表',
                'req.body.ci':'公会公告,Club表',
                'req.body.uid':'用户id,User表'
            },
            'return':{
                '成功失败与错误码':1,
                'cid':'公会id'
            }
        }
    },
    '/clubApplyByUserId':{
        'post':{
            'desc':'申请公会',
            'param':{
                'req.body.cid':'公会id,Club表',
                'req.body.uid':'用户id,User表'
            },
            'return':{
                '成功失败与错误码':1
            }
        }
    },
    '/clubApplyByUserId':{
        'post':{
            'desc':'申请公会',
            'param':{
                'req.body.cid':'公会id,Club表',
                'req.body.uid':'用户id,User表'
            },
            'return':{
                '成功失败与错误码':1
            }
        }
    },
    '/joinClubByUserId':{
        'post':{
            'desc':'加入公会',
            'param':{
                'req.body.cid':'公会id,Club表',
                'req.body.auid':'加入的用户id,User表',
                'req.body.uid':'用户id,User表',
            },
            'return':{
                '成功失败与错误码':1
            }
        }
    },
    '/appointClubManager':{
        'post':{
            'desc':'任命',
            'param':{
                'req.body.job':'公会职位,Club表',
                'req.body.auid':'加入的用户id,User表',
                'req.body.uid':'用户id,User表'
            },
            'return':{
                '成功失败与错误码':1
            }
        }
    },
    '/exitClub':{
        'post':{
            'desc':'退出公会',
            'param':{
                'req.body.uid':'用户id,User表'
            },
            'return':{
                '成功失败与错误码':1
            }
        }
    },
    '/modifyClubCopy':{
        'post':{
            'desc':'更新副本',
            'param':{
                'req.body.cid':'公会id,Club表',
                'req.body.uid':'用户id,User表'
            },
            'return':{
                '成功失败与错误码':1
            }
        }
    },
    '/openCopy':{
        'post':{
            'desc':'开启副本',
            'param':{
                'req.body.cid':'公会id,Club表',
                'req.body.idx':'公会的副本的索引id,Club表'
            },
            'return':{
                '成功失败与错误码':1
            }
        }
    },
    '/getCopy':{
        'get':{
            'desc':'获取副本',
            'param':{
                'req.body.cid':'公会id,Club表',
                'req.body.idx':'公会的副本的索引id,Club表'
            },
            'return':{
                '成功失败与错误码':1,
                'cr':'副本的记录信息',
                'cp':'副本的藏宝图碎片',
                'cpt':'副本的每日限制次数'
            }
        }
    },
    '/getAllFriend':{
        'get':{
            'desc':'获取好友',
            'param':{
                'req.body.uid':'用户id,Club表'
            },
            'return':{
                '成功失败与错误码':1,
                'd':'好友数据'
            }
        }
    },
    '/addFriend':{
        'post':{
            'desc':'添加好友',
            'param':{
                'req.body.uid':'好友id,friend表',
                'req.body.auid':'好友id,friend表',
                'req.body.n1':'好友名称1,friend表',
                'req.body.n2':'好友名称2,friend表'
            },
            'return':{
                '成功失败与错误码':1
            }
        }
    },
    '/modifyFriend':{
        'post':{
            'desc':'更新好友',
            'param':{
                'req.body.uid':'用户id,user表',
                'req.body.f1':'好友id,friend表',
                'req.body.f2':'好友id,friend表',
                'req.body.e':'赠送体力状态,friend表',
                'req.body.s':'邀请技能状态,friend表'
            },
            'return':{
                '成功失败与错误码':1
            }
        }
    },
    '/removeFriendByFid':{
        'post':{
            'desc':'删除好友',
            'param':{
                'req.body.uid':'用户id,user表',
                'req.body.f1':'好友id,friend表',
                'req.body.f2':'好友id,friend表'
            },
            'return':{
                '成功失败与错误码':1
            }
        }
    },
    '表结构':{
        'User':{
            'desc':'用户',
            'values':{
                'un':'账号名',
                'pwd':'密码',
                'token':'第三方平台同行凭证',
                'platform':'平台ID',
                'platformuuid':'平台用户UUID'
            }
        },
        '/UserStatistics':{
            'desc':'统计数据',
            'values':{

            }
        },
        'UserDetail':{
            'desc':'用户存档信息',
            'values':{
                'nn' : '昵称,字符串',
                "g" : '性别,数字',
                "uid" : "unique id,字符串",
                "zid" : '区域id,数字',
                "eng" : '当前体力,数字',
                "teng" : '体力上限,数字',
                "lem" : '最新更新体力时间戳',
                "cem" : '最新开始计时体力时间点的时间戳',
                "nd" : '新手任务步骤',
                'm':'money,数字',
                'c':'coin,数字',
                'p':'progress,字符串',
                's':'stage,数字',
                'cs':'city_status,字符串',
                't':'token,令牌数,数字',
                "task" : {
                    'desc':'任务数据,键值对列表',
                    't+任务ID':{
                        'am1':'已完成任务步骤1计数,数字',
                        'am2':'已完成任务步骤2计数,数字',
                        'st':'任务状态,数字'
                    }
                },
                "ci" : {
                    'desc':'案件数据,键值对列表',
                    'c+案件ID':{
                        'cr':'案件记录,字符串,形如:场景id_等级_最高分_当前总分数`场景id_等级_最高分_当前总分数`...',
                        'lid':'案件完成的最后任务线的任务id,数字',
                        'cst':'案件状态,数字',
                        'ct':'案件完成任务顺序 case task sequence',
                        'cat':'案件接受任务顺序 case accept task sequence'
                    }
                },
                "ts" : {
                    'desc':'鉴证开始时间戳',
                    'c+案件ID':{
                        'i+物品ID':'这个物品开始鉴证时间戳,数字,后续重复格式'
                    }
                },
                "sr":{
                    'desc':'签到记录',
                    'd':{
                        'desc':'签到数据',
                    },
                    'seq':{
                        'desc':'连续签到记录',
                        'days':'当前这个追踪已连续签到多少天'
                    }
                },
                "gid":1,// 公会ID
                "flst":[{
                    // 好友列表
                }],
                "ars":{
                    'desc':'活动追踪'
                }
            }
        },
        'errorCode':{
            UserNameExist:'1 用户名存在',
            UserPasswordWrong:'2 用户名或密码错误',
            NoRoleInZone:'3 该区域内无角色',
            EnergyFull:'4 体力已满不能增加',
            NoReadyAddEnergy:'5 时间未到不能增加体力',
            EnergyNotEnough:'6 体力不足',
            UnExistedEvidence:'7 证物不存在',
            EvidenceNotReady:'8 证物未鉴定完',
            RoleExistInZone:'9 角色已存在本区域内',
            ParamWrong:'10 参数错误',
            NoEnoughGemCompleteEvidence:'11 无法立即完成鉴定',
            RoleNameExist:'12 角色名在该服务器已存在',
            UserNameFormatWrong:'13 用户名格式错误',
            PasswordFormatWrong:'14 密码格式错误',
            CaseNotExist:'15 目标案件不存在',
            IllegalRequestParam:'16 非法请求参数',
            NullRoleData:'17 角色数据不存在',
            WrongLoginInfo:'18 错误的登陆验证信息,请重新登陆',
            ErrorUDID:'19 错误的或者空的udid',
            AlreadyBindedUsername:'20 已绑定的账号名',
            WrongTourAccount:'21 不存在的游客账号'
        }
    }
};